rootProject.name = "rpg-engine"

include(":common")
include(":identity-module")
include(":character-module")
include(":combat-module")
include(":skill-module")
include(":item-module")
include(":economy-module")
include(":infrastructure-module")
include(":quest-module")
include(":dungeon-module")
include(":world-module")
include(":achievement-module")
include(":minecraft-adapter")
include(":bootstrap-plugin")
